// ─────────────────────────────────────────────────────────────────────────────
// Postly — Shared Agent Contracts
// All agents receive AgentContext and return AgentResult<T>
// ─────────────────────────────────────────────────────────────────────────────

// Aligned with neuropost/src/types/index.ts — must stay in sync
export type SocialSector =
  | 'heladeria' | 'restaurante' | 'cafeteria' | 'gym' | 'clinica' | 'barberia' | 'boutique' | 'inmobiliaria'
  | 'panaderia' | 'cocteleria' | 'street_food' | 'vinoteca'
  | 'nail_art' | 'estetica' | 'maquillaje'
  | 'moda_hombre' | 'zapateria' | 'skincare'
  | 'yoga' | 'dental' | 'clinica_estetica' | 'nutricion'
  | 'decoracion' | 'jardineria' | 'reformas' | 'inmobiliaria_lujo'
  | 'fotografia' | 'academia' | 'abogado' | 'veterinario' | 'mecanica'
  | 'teatro' | 'arte' | 'libreria' | 'gaming' | 'viajes' | 'hotel'
  | 'floristeria' | 'regalos' | 'tecnologia'
  | 'otro';

export type SubscriptionPlan = 'starter' | 'pro' | 'total' | 'agency';
/** @deprecated Use SubscriptionPlan */
export type SubscriptionTier = SubscriptionPlan;

export type BrandTone = 'cercano' | 'profesional' | 'divertido' | 'premium';

/**
 * Voice and personality document for a business.
 * Passed as context to every agent so outputs stay on-brand.
 */
export interface BrandVoice {
  tone: BrandTone;
  /** Words and themes to actively include */
  keywords: string[];
  /** Words and themes to never use */
  forbiddenWords: string[];
  sector: SocialSector;
  /** BCP-47 language tag, e.g. 'es', 'en', 'ca' */
  language: string;
  /** 2-5 real captions from the brand for style reference */
  exampleCaptions: string[];
}

export interface SocialAccounts {
  instagramId?: string;
  facebookPageId?: string;
  /** Meta Graph API long-lived access token */
  accessToken: string;
}

/**
 * Full context injected into every agent call.
 * Agents are stateless — all business data lives here.
 */
export interface AgentContext {
  businessId: string;
  businessName: string;
  brandVoice: BrandVoice;
  socialAccounts: SocialAccounts;
  /** IANA timezone, e.g. 'Europe/Madrid' */
  timezone: string;
  subscriptionTier: SubscriptionPlan;
  /** Full brand voice document generated by the brand kit editor */
  brandVoiceDoc?: string;
}

// ─── Result envelope ──────────────────────────────────────────────────────────

export interface AgentError {
  code: string;
  message: string;
  /** Whether the caller should retry this operation */
  retryable: boolean;
}

export interface AgentMetadata {
  agentName: string;
  executionId: string;
  durationMs: number;
  timestamp: string;
  tokensUsed?: number;
}

export interface AgentResult<T> {
  success: boolean;
  data?: T;
  error?: AgentError;
  metadata: AgentMetadata;
}
