-- =============================================================================
-- content_queue table
-- Holds posts that have been generated by AI and are awaiting worker review
-- before being sent to the client.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.content_queue (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id             uuid        NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  brand_id            uuid        NOT NULL REFERENCES public.brands(id) ON DELETE CASCADE,
  status              text        NOT NULL DEFAULT 'pending_worker'
                                  CHECK (status IN (
                                    'pending_worker',
                                    'sent_to_client',
                                    'worker_rejected',
                                    'client_approved',
                                    'client_rejected',
                                    'auto_approved_ai'
                                  )),
  priority            text        NOT NULL DEFAULT 'normal'
                                  CHECK (priority IN ('normal', 'urgent')),
  worker_notes        text,
  worker_reviewed_at  timestamptz,
  assigned_worker_id  uuid        REFERENCES public.workers(id) ON DELETE SET NULL,
  ai_review           jsonb,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

-- Index for common query patterns
CREATE INDEX IF NOT EXISTS content_queue_status_idx    ON public.content_queue (status);
CREATE INDEX IF NOT EXISTS content_queue_brand_id_idx  ON public.content_queue (brand_id);
CREATE INDEX IF NOT EXISTS content_queue_post_id_idx   ON public.content_queue (post_id);
CREATE INDEX IF NOT EXISTS content_queue_priority_idx  ON public.content_queue (priority DESC, created_at ASC);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION public.set_content_queue_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS content_queue_updated_at ON public.content_queue;
CREATE TRIGGER content_queue_updated_at
  BEFORE UPDATE ON public.content_queue
  FOR EACH ROW EXECUTE FUNCTION public.set_content_queue_updated_at();

-- =============================================================================
-- Row Level Security
-- =============================================================================

ALTER TABLE public.content_queue ENABLE ROW LEVEL SECURITY;

-- Service role bypasses RLS entirely (used by server-side admin client)
-- No explicit policy needed — service_role bypasses RLS by default in Supabase.

-- Workers can read all queue items
CREATE POLICY "workers_read_all_queue"
  ON public.content_queue
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.workers w
      WHERE w.user_id = auth.uid()
    )
  );

-- Workers can update queue items for brands assigned to them
CREATE POLICY "workers_update_assigned_brands"
  ON public.content_queue
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.workers w
      WHERE w.user_id = auth.uid()
        AND (
          w.role IN ('admin', 'senior')
          OR brand_id = ANY(w.brands_assigned)
        )
    )
  );

-- Workers can insert new queue items (e.g., re-queueing)
CREATE POLICY "workers_insert_queue"
  ON public.content_queue
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.workers w
      WHERE w.user_id = auth.uid()
    )
  );
